language: go

go:
  - 1.11
  
branches:
  only: master

notifications:
  irc:
    channels:
      - "irc.freenode.net#cgrates"
    on_success: change
    on_failure: always
  email:
    on_success: never
    on_failure: always

